[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 2000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_PROJECT_ID}"
lyra = "https://rpc.lyra.finance"
lyra_testnet = "https://l2-prod-testnet-0eakp60405.t.conduit.xyz"