name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Submodules
        run: git submodule update --init --recursive
  
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      
      - name: Run tests
        run: forge test -vvv --fork-url https://rpc.lyra.finance